version: '3'  # 你可以根据需要选择合适的版本
services:
  jobmanager:
    image: flink:1.15.0-scala_2.12-java8
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    command: jobmanager
    networks:
      - flink-network

  taskmanager1:
    image: flink:1.15.0-scala_2.12-java8
    container_name: flink-taskmanager1
    environment:
        - |
         FLINK_PROPERTIES=
         jobmanager.rpc.address: jobmanager
         taskmanager.numberOfTaskSlots: 2
    command: taskmanager
    depends_on:
      - jobmanager
    networks:
      - flink-network

  taskmanager2:
    image: flink:1.15.0-scala_2.12-java8
    container_name: flink-taskmanager2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    command: taskmanager
    depends_on:
      - jobmanager
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge

